include: package:flutter_lints/flutter.yaml

analyzer:
linter:
  rules:
    # ---------- STYLE ----------
    prefer_single_quotes: true
    curly_braces_in_flow_control_structures: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_full_hex_values_for_flutter_colors: true

    # ---------- BEST PRACTICES ----------
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_returning_null_for_future: true
    avoid_void_async: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_final_in_for_each: true

    # ---------- NULL SAFETY ----------
    avoid_null_checks_in_equality_operators: true
    unnecessary_null_checks: true
    unnecessary_nullable_for_final_variable_declarations: true

    # ---------- PERFORMANCE ----------
    use_key_in_widget_constructors: true
    avoid_slow_async_io: true

    # ---------- READABILITY ----------
    always_declare_return_types: true
    type_annotate_public_apis: true
    avoid_types_as_parameter_names: true
